### ISSUE TITLE
Multithreading support

### ISSUE THREAD

**Issue by TOXid** [arkmanager/ark-server-tools#624]
Does anyone know how to run the server in the multi-threaded? At the 4 core system it is loaded, or 1 core by 100% or 4 cores by 25% ...

**Comment by klightspeed** [comment]
https://answers.unrealengine.com/questions/39154/why-does-epic-always-make-dedicated-server-single.html

The Unreal Engine Dedicated Server uses a single thread for physics.

https://forums.unrealengine.com/showthread.php?62272-Linux-Server-multi-core-thread-support

If Wildcard doesn't use worker threads, then the server will only use a single thread for game code.

**Comment by KGM6911** [comment]
I've read over this a number of times in the past when you posted it as a reply to this type of question.  I honestly don't understand what it means.  What I think is that you can only run the game in a single core.  What I'd like to know is if you are running multiple servers on the same machine are you able to run each server in it's own core?

**Comment by klightspeed** [comment]
So you're wanting to set up CPU affinity?  Something like a `arkCpuAffinity` setting that uses `taskset` to set the CPU affinity?

The Linux scheduler should generally assign cores to processes intelligently.

**Comment by KGM6911** [comment]
So when you say "The Linux scheduler should generally assign cores to processes intelligently." I take that I shouldn't touch it.  It will manage itself properly.  Thanks!

**Comment by klightspeed** [comment]
Commit `60465a1` (which will be in v1.6.05) adds the `arkCpuAffinity` setting, which uses [`taskset`](https://linux.die.net/man/1/taskset)

**Comment by KGM6911** [comment]
In regard to the arkCpuAffinity, my server is running the following:  Intel i7-4790K 4 Cores / 8 Threads.  I'm running three ark servers on it.  Would I benefit from using the arkCpuAffinity setting?

And would I use it by adding something like this to the instance files?

arkCpuAffinity=1,2  (added to the instance file of my most popular server - This one allows for using 2 of the cores)
arkCpuAffinity=3     (added to my second instance file)
arkCpuAffinity=4     (added to my third instance file)

Is the above correct?   And do you recommend doing this? 
Thanks

**Comment by klightspeed** [comment]
I would set `arkCpuAffinity=0,2` for your popular instance, and `arkCpuAffinity=4-7` for your less-popular instances.  "processor" numbers include threads, and start at 0.  `0,2` should choose the first thread of each of the first two cores, and `4-7` should use both threads of the third and fourth cores.

**Comment by KGM6911** [comment]
Great, thanks!    I also run one other box.   It's got more cores and threads.  Could you recommend settings for it also?

Intel E5-1650v2 6 Cores / 12 Threads

Same thing, 3 servers on it.
Thanks!

**Comment by klightspeed** [comment]
The idea with giving the popular server threads 0 and 2 is so that the server thread(s) are not both trying to run simultaneously on the same core.

If you want to give your popular server 2 cores, then set the cpu affinity for that server to e.g. `0,2`.

If you want to give the rest of the servers the remaining cores, then set their CPU affinity to `4-11`

Assuming the physics runs on one thread and the game loop on another loop, it isn't much use giving any of the servers more than 2 cores.

**Comment by KGM6911** [comment]
Thank you!  I had removed because I don't want to drive you crazy!   Appreciate all the great info.. I'm new to Linux.. Only a few weeks.. Love it so far!

**Comment by KGM6911** [comment]
I see that using 4-7 or 4-11 uses everything between them, but I'm curious about 0,2.  Does this mean it leaves one core out?  Is this for OS?  Is there a reason it's not at the start?  I've put the 0,2 and 4-7 on the one server and tried to start it up.  It didn't seem to want to start so I aborted it and rebooted the server and they started right up.

**Comment by klightspeed** [comment]
0 and 1 refer to the threads on the first core.
2 and 3 refer to the threads on the second core.

Note that the systemd service startup doesn't currently use `arkCpuAffinity` or `arkPriorityBoost`

The apparent hang on startup should be fixed with commit 5405c64.

**Comment by KGM6911** [comment]
I'm still not able to use arkmanager start @all.  It just hangs.  If I reboot the machine then the instances are started.

**Comment by KGM6911** [comment]
And when I run arkmanager upgrade-tools it says it's up to date.  I verified with arkmanager --version

**Comment by KGM6911** [comment]
Ok, maybe i'm wrong that I have the latest... Here's output:
arkmanager --version
Version: 1.6
Channel: master
Commit: 4a2699b
Release Tag: v1.6.05

That commit wasn't from today.   Here's what I see when I try to update:

arkmanager upgrade-tools
arkmanager v1.6: Checking for updates...
Getting latest release...
Your ARK server tools are already up to date

**Comment by KGM6911** [comment]
Ok, figured it out.. I edited the file and put the sleep 1 in myself and now it's working.  I guess not all commits go to updates.. Sorry for all the posts!

**Comment by klightspeed** [comment]
I haven't put the commits fixing these into a release yet.

**Comment by KGM6911** [comment]
Started getting this error when starting the servers:

Running command 'start' for instance 'scorched-pvp'
The server is starting...
Setting CPU affinity for ark server
taskset: failed to execute -p: No such file or directory
The server is now running, and should be up within 10 minutes

I get this in my arkserver.log file:

**Comment by KGM6911** [comment]
2016-10-06 16:49:08: Running /home/steam/scorched-pvp/ShooterGame/Binaries/Linux/ShooterGameServer ScorchedEarth_P\?RCONEnabled=True\?RCONPort=27020\?Port=7777\?QueryPort=27015\?ServerPassword\?ServerAdminPassword=\?MaxPlayers=50\?AltSaveDirectoryName=SavedArk-scorched-pvp\?AlwaysRestartOnCrash=true\?TribeLogDestroyedEnemyStructures=True\?TamingSpeedMultiplier=10.000000\?HarvestAmountMultiplier=6.000000\?StructurePreventResourceRadiusMultiplier=1.000000\?PerPlatformMaxStructuresMultiplier=1.000000\?ListenServerTetherDistanceMultiplier=1.000000\?MaxTamedDinos=3000.000000\?RCONServerGameLogBuffer=600.000000\?AllowHitMarkers=True\?PreventDownloadItems=True\?PreventDownloadDinos=True\?ShowMapPlayerLocation=true\?ServerForceNoHUD=false\?GlobalVoiceChat=false\?ProximityChat=false\?AllowThirdPersonPlayer=false\?AlwaysNotifyPlayerLeft=false\?DontAlwaysNotifyPlayerJoined=true\?ServerHardcore=false\?ServerPVE=false\?ClampResourceHarvestDamage=False\?DifficultyOffset=1.000000\?AdminLogging=True\?ForceAllStructureLocking=True\?XPMultiplier=4.0\?PvPStructureDecay=true\?PreventTribeAlliances=true\?ServerCrosshair=false\?RaidDinoCharacterFoodDrainMultiplier=1.000000\?AutoSavePeriodMinutes=15\?PvEDinoDecayPeriodMultiplier=1.000000\?listen -NoTransferFromFiltering -clusterid=ApocCrossArkPVP -UseBattlEye
2016-10-06 16:49:08: Server PID: 25634
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Setting breakpad minidump AppID = 346110
2016-10-06 16:49:45: server is up

Not sure if these things have anything to do with one another...   The only change I've made to my server recently was cleaned up my firewall and put a block on all other IPv4 traffic that isn't in my accepted ports.

**Comment by klightspeed** [comment]
v1.6.06 should fix the taskset -p error.

**Comment by KGM6911** [comment]
Thanks, that fixed it!

**Comment by Gumballz** [comment]
I maybe wrong, but i don't think you need to assign the servers to any threads/cores.

If you run $ top -p <pid>  
then press f and add the *Last Used CPU (SMP)* and *Number of Threads* columns,  you will notice it reports 16 (for me) threads used and the core will change every few seconds to a different core.

adding additional -p <pid> (for each instance)  will generally show them using different cores.
